### PR TITLE
Add Scenario of " SolarWinds Breach"

### PR DESCRIPTION
**Pull request by alaanasser00**
Information extracted from: https://www.picussecurity.com/resource/blog/ttps-used-in-the-solarwinds-breach

### CODE REVIEW

**Comment by alaanasser00** [comment]
Thank you @sanchezmia for your time to write this detailed response. I'll make sure to add these changes.

**Comment by mehaase** [comment]
Hi @alaanasser0, we have some interest in completing the SolarWinds flow -- are you okay if we update this flow on your behalf? We would still list you as a co-author.

**Comment by alaanasser00** [comment]
Hi @mehaase, sure! I wanted to complete it but unfortunately I don't have enough time to focus on it. 
Nevertheless, hit me up if you need any help.
Have a great weekend.

**Comment by mehaase** [comment]
The SolarWinds flow has been upgraded to Attack Flow v2 and included in today's public release. Thank you @alaanasser00 and @sanchezmia!

**Pull request closed without merging**
